### ISSUE TITLE
Engine datasource dependency

### ISSUE THREAD

**Issue by avimora** [CloudSlang/score#18]
1. Minimize direct dependencies on `dataSource` (`HiloFactoryBean`, `DataBaseDetector` and `ExecutionQueueRepositoryImpl`)
2. Use `@Resource` instead of `@Autowired`
3. Consider supporting custom `dataSource` name
4. Consider these point for other DB related stuff (`jdbcTemplate` etc)

**Comment by orius123** [comment]
why is `@Resource` better if we are not specifying a qualifier?

**Comment by avimora** [comment]
With `@Resource` the resolution is done preliminary by name. Besides it's standard javax and recommended by spring.
Suggestion: Pass the ds name through `EngineBeanDefinitionParser`
