### ISSUE TITLE
worker

### ISSUE THREAD

**Issue by levystasman** [CloudSlang/score#190]
I am a newbie to Cloudslang.

a) How to configure more workers?
b) How to configure worker to specific queue in order to act on  jobs sent to that queue?

Thanks

**Comment by levystasman** [comment]
Any help on this?

**Comment by lucian-cm** [comment]
Hi @levystasman,

You can read more about the architecture of CloudSlang at https://cloudslang-docs.readthedocs.io/en/latest/developer/developer_architecture.html?highlight=worker.

There is a global queue, each worker will execute messages that are assign to it.
There is no out of the box configuration for multiple workers, please go over the `hello-score` sample.

Each worker must have a unique `uuid` to each worker. 
e.g. `<score:worker uuid="e5db3bd6-6bb4-4619-adcf-3922296e516c"/>`
For the engine element make sure that you use `externalDatabase` to true.
e.g. 
`<score:engine externalDatabase="true">`
To set your dataSource change `dataSource` method from `io.cloudslang.schema.context.ScoreDefaultDatasourceContext`.

**Comment by levystasman** [comment]
@lucian-cm Appreciate your prompt response, i will take a look. Thanks

**Comment by levystasman** [comment]
@lucian-cm As I explore, one simple question 

a) Is there any specific settings I need to do in a specific config file to spin multiple workers
b) In you example I see <score:worker uuid="e5db3bd6-6bb4-4619-adcf-3922296e516c"/> from where/how the uuid gets created and assigned

**Comment by lucian-cm** [comment]
@levystasman just generate a uuid 
https://onlinerandomtools.com/generate-random-uuid
or from java `UUID.randomUUID().toString()` and create an score:worker bean and assign the uuid to it.

**Comment by levystasman** [comment]
@lucian-cm Thank you
