### ISSUE TITLE
Rapid running of busyWorkersService

### ISSUE THREAD

**Issue by srinisubramanian** [CloudSlang/score#369]
The busyWorkersService seems to run by default at intervals of 200 milli seconds configured in scoreEngineSchedulerContext.xml (from score-all)

This rapid run is adding to load on the database.

Qn 1:  Can this interval (safely) be changed to for e.g 5 seconds?
Qn 2:  Since its in the XML , teh XML has to be patched into the jar I guess after changing the config?  Are there any other options to reconfigure?

**Comment by srinisubramanian** [comment]
Bump... Can anyone help?

**Comment by lucian-cm** [comment]
Hi @srinisubramanian 

Can you explain why 200 milliseconds does not work for your use case? 5 seconds is too big of a value imo, it means that score engine might have pending execution messages that are delayed by 5 seconds. 
Right now the settings is hidden and hence not configurable as it is deemed an internal score engine concern.

**Comment by srinisubramanian** [comment]
@lucian-cm  it's simply loading the database. Too many queries hitting it and our customer IT admin is complaining :)

I thought this was just to recover busy threads and real execution of workflow is controlled by the workers.inbuffer.coolDownPollingMillis which is a system property and default to 200ms

**Comment by lucian-cm** [comment]
You can go in the middle with a value in the range [500..2000] and see if the 'hit rate' decreases.

**Comment by srinisubramanian** [comment]
Thanks @lucian-cm I will try that. Out of curiosity can you take a minute and explain what that busyworkerservice is doing. I guess it is not to poll the queue for workflows to execute but more to recover?

**Comment by lucian-cm** [comment]
BusyWorkerService is orchestrator local map to know if new execution messages in status ASSIGNED have arrived for any worker. This map is completely refreshed every 200 ms.

**Comment by srinisubramanian** [comment]
Thanks @lucian-cm That means once a workflow is triggered this controls how quickly that is picked up for execution?

**Comment by lucian-cm** [comment]
yes

**Comment by srinisubramanian** [comment]
Thanks. Am closing the issue also.
