### ISSUE TITLE
Enchancement - API for score / cloudslang only

### ISSUE THREAD

**Issue by mbettan** [CloudSlang/score#77]
Hello,

Many customers are requring for an API available for CloudSlang

Can we add this to backlog, is it already planned, i notice 'score-api' folder commited?

Thanks for let me know

**Comment by Bonczidai** [comment]
@mbettan could you specify here what do you mean by API?

CloudSlang already has an API in [io.cloudslang.lang.api](https://github.com/CloudSlang/cloud-slang/tree/master/cloudslang-all/src/main/java/io/cloudslang/lang/api) package called [Slang](https://github.com/CloudSlang/cloud-slang/blob/master/cloudslang-all/src/main/java/io/cloudslang/lang/api/Slang.java) when embedding CS as a library. It has methods like compiling & running flows, working with events & metadata. Upper modules like CLI, builder, a webapp, other apps that integrate CS are supposed to communicate through this API.

also, if you are interested, here is an example [app](https://github.com/natabeck/slang-webapp) that integrates CS an disposes a REST API..

**Comment by mbettan** [comment]
All customers are looking for executing CSlang workflows from API instead of using CLI for executing workflows. It seems that's already available, why it's not documented officially ? Which operations are available today?

**Comment by Bonczidai** [comment]
doc on how to embed CS as a library (api and stuff): http://cloudslang-docs.readthedocs.org/en/v0.9/developer_cloudslang.html

you can execute any flow / op using CS API just like in the case of the CLI

if you have enhancement ideas on the subjects, let us know :bowtie:

**Comment by mbettan** [comment]
It's only JAVA API available ? We don't have a standard REST API like OO?

**Comment by orius123** [comment]
for a RESTful API you can use the example app @Bonczidai linked above, if something is missing/outdated there feel free to open a PR/issue in this project, I know there were plans for making an API, but don't know when it is going to happen.

**Comment by mbettan** [comment]
Yes - That's why I opened this issue to add this to BackLog

All customers are requiring this, JAVA API is a good start, but really need a RESTful API

Can you add this as ER to backlog?

**Comment by Bonczidai** [comment]
opened the issue in cloud-slang repo and added to the backlog, closing this one

**Comment by lrevnic** [comment]
Do you have details on the customer requirements around this REST API? 
What do they want to do: Run management, Scheduling, Promotion, Edit flows etc.?

@mbettan one way to achieve some of the  aboves today is to use OO 10.50 REST APIs  can be used to trigger/monitor/schedule CloudSlang flows in the same way you do for the OO flows.

**Comment by mbettan** [comment]
Yes - All prospects are requiring an API for running workflows at least. I would say that edit flows, promotion, scheduling are optionnal at this stage. Basic workflows run from outside is a must have

Yes - I now that OO Enterprise can be the API for CloudSlang, but remember two things 
1) OO 10.50 doesn't support our current CloudSlang release with new YAML langage
2) All CloudSlang customers or prospects are not OO Enterprise users

This RESTFul API is a must have today

**Comment by lrevnic** [comment]
Yeap. Another option would be to use/demo OO 10.50 Community Edition (free) to run, schedule etc CloudSlang flows. I got your point that the users may be different than OO ones.

**Comment by mbettan** [comment]
You cannot explain to Opensource users they have to use a proprietary solution for getting a Restful API.
Some customers told me that the good way could be also to leverage Docker API to start a docker image with CloudSlang CLI, as workaround.

**Comment by orius123** [comment]
there is a cloudslang image, how  does it solve the API issue though?

**Comment by mbettan** [comment]
Docker Engine provides an API to start a Docker container.  Then, you can query Docker APi to start Docker CloudSlang Image, which contains your workflows and will be executed at start-up

It' my customer idea, not mine. Not sure it's a good idea
